//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatisVeRezervasyonSistemi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiletRezervasyonDBEntities : DbContext
    {
        public BiletRezervasyonDBEntities()
            : base("name=BiletRezervasyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBilet> TBilet { get; set; }
        public virtual DbSet<TOtobus> TOtobus { get; set; }
        public virtual DbSet<TRezervasyon> TRezervasyon { get; set; }
        public virtual DbSet<TYolcu> TYolcu { get; set; }
        public virtual DbSet<TYonetici> TYonetici { get; set; }
        public virtual DbSet<TKoltuk> TKoltuk { get; set; }
        public virtual DbSet<TSefer> TSefer { get; set; }
    }
}
