//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatisVeRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBilet
    {
        public int BiletID { get; set; }
        public string No { get; set; }
        public Nullable<int> Otobus { get; set; }
        public Nullable<int> Kisi { get; set; }
        public Nullable<int> Koltuk { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> OlusumTarih { get; set; }
    
        public virtual TOtobus TOtobus { get; set; }
        public virtual TYolcu TYolcu { get; set; }
        public virtual TKoltuk TKoltuk { get; set; }
    }
}
