//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatisVeRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKoltuk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKoltuk()
        {
            this.TBilet = new HashSet<TBilet>();
            this.TRezervasyon = new HashSet<TRezervasyon>();
        }
    
        public int KoltukID { get; set; }
        public string KoltukNo { get; set; }
        public Nullable<int> Otobus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBilet> TBilet { get; set; }
        public virtual TOtobus TOtobus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRezervasyon> TRezervasyon { get; set; }
    }
}
