//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatisVeRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYolcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYolcu()
        {
            this.TBilet = new HashSet<TBilet>();
            this.TRezervasyon = new HashSet<TRezervasyon>();
        }
    
        public int YolcuID { get; set; }
        public string KisiBilgi { get; set; }
        public string Telefon { get; set; }
        public string Parola { get; set; }
        public string KullaniciAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBilet> TBilet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRezervasyon> TRezervasyon { get; set; }
    }
}
